### ISSUE TITLE
Feature request: Expose bytes of encoded tbsCertificate

### ISSUE THREAD

**Issue by jannschu** [rusticata/x509-parser#13]
Hi,

for checking the signature the encoded representation of cbsCertificate is needed. I would suggest to add api to expose this representation.

I think this can be implemented with a nom combinator similar to `recognize`. If you interested in this, I can create a pull request.

**Comment by chifflier** [comment]
Hi,
I like the idea of exposing the raw bytes!
I'll comment more on the PR, but I'm not exactly sure `recognize` is the easiest way to do it (even if technically it would work). Just comparing the bytes offsets should be enough (nom has an `Offset` trait for that)

Note: it seems someone else did a similar job in #16
