### ISSUE TITLE
Provide parsing for major extensions

### ISSUE THREAD

**Issue by jannschu** [rusticata/x509-parser#15]
Hi,

I suggest to add parsing support for the most important extensions, for example the ones listed here: https://developer.mozilla.org/en-US/docs/Mozilla/Security/x509_Certificates#Extensions_2.

Some rudimentary parsing for certificate policies would be nice, too.

To implement this one could make the `X509Extension` an enum which I think would result in the easiest api. I will start working on this.

**Comment by chifflier** [comment]
That is indeed the objective.
I would like to do something similar to https://github.com/rusticata/tls-parser/blob/master/src/tls_extensions.rs for TLS (though, if there are improvements to do, the TLS extensions code is not considered perfect and can be discussed/changed)

**Comment by chifflier** [comment]
Many extensions are now supported in version 0.8.0 (just released). Others will be added later.

I'll check if this this is enough for most use cases, and close this issue later.

**Comment by jannschu** [comment]
Thanks! Sorry I could not help with the pull request :-(

**Comment by chifflier** [comment]
It has been some time now, and all extensions listed (and more) in https://developer.mozilla.org/en-US/docs/Mozilla/Security/x509_Certificates#extensions_2 have been implemented in 0.9.0, so I'm closing this issue.
Feel free to open new issues if other extensions are missing.
