### ISSUE TITLE
Open for maintainers?

### ISSUE THREAD

**Issue by reubenmiller** [rusticata/x509-parser#150]
A friendly question whether additional maintainers can help assist with the maintenance of the project, like fixing clippy warnings, updating dependencies etc.

The project is currently used under some larger projects, making the motivation to be able to update core dependencies like [briansmith/ring](https://github.com/briansmith/ring) etc.
 
Example projects which currently using this project:

* https://github.com/rustls/rcgen

Just looking at some of the approvers, contributors might be useful to gauge "who" would be good candidates (if they are willing to accept).

**Comment by cpu** [comment]
I would be happy to volunteer to help if there's interest. I've been helping maintain Rcgen and various Rustls projects and have a decent amount of PKI and X.509 experience from Let's Encrypt, ACME and ZLint.

**Comment by cpu** [comment]
Pierre and I were able to discuss this and I now have more permissions to help with maintenance. I'm going to close this issue for now but if there are others interested in helping out we could certainly revisit :-)
