### ISSUE TITLE
Can't parse pem certificate if the section "Bag Attributes" is provided.

### ISSUE THREAD

**Issue by AlexFdv** [rusticata/x509-parser#21]
The function pem_to_der can't parse pem file if the section "Bag attributes" is provided.

The pem certificate can look like this:

> Bag Attributes
>     localKeyID: B9 FD 3E 10 61 18 CD D3 27 A3 8D F4 97 C6 2D 1C 4A 7C A0 6C 
> subject=/C=AU/ST=Some-State/O=/CN=
> issuer=/C=AU/ST=Some-State/O=/CN=
> -----BEGIN CERTIFICATE-----
> <base_64>
> -----END CERTIFICATE-----

**Comment by jannschu** [comment]
The function `pem_to_der` expects the certificate to start with `-----BEGIN`.
