### ISSUE TITLE
Upgrade `time` crate

### ISSUE THREAD

**Issue by chifflier** [rusticata/x509-parser#26]
`time` crate has new releases (0.2.6), but also major API changes.

**Comment by chifflier** [comment]
I'm going to work on that to avoid lagging in versions.
It is not possible to upgrade to the new `time` crate, its new version lacks features (like parsing the "Z" timezone), so I'm moving to `chrono`.
However, this will break existing API for checking certificate validity :/

Add @jannschu @g2p @wayofthepie

**Comment by chifflier** [comment]
Additional note: crates to manage time/dates seems to be in a quite unstable state on crates.io
To avoid new problems in the future, best would be to abstract time objects.

**Comment by chifflier** [comment]
The main part of the change is done in 559f7072d947ff4d37193b3834d00f90d22b5e80

However, before closing I'll try to think of an abstraction layer to avoid breaking API in the future

**Comment by g2p** [comment]
My preference would be to expose only parsing/formatting, and feature gate the existing functions that require a clock and call now(). The same functions can still be exposed as `valid_at` taking a datetime argument.

That way, the application can pick its time source, and maybe pick its poison wrt the three incompatible versions of the `time` crate (0.3 is coming up soon).

I'll check if chrono is usable with its clock feature (adding a dependency on time 0.1) disabled.

**Comment by chifflier** [comment]
@g2p : I was just about to commit that. I just implemented an abstraction over this, so the underlying crate (`chrono`) is not exposed, so it should fit your needs.
The API coverage has to be tested (it does have `now()`, and I updated the unit tests that checks validity, so I think it should be ok).

**Comment by chifflier** [comment]
Closing issue, everything has been upgraded
