### ISSUE TITLE
Can it parse Version1 x509 certs.

### ISSUE THREAD

**Issue by amrx101** [rusticata/x509-parser#31]
First of all, thanks for the amazing work. 

I had one query, can it parse version 1 x509 certificates?

If not and if I want to add that support where should I start looking at in the code-base?

**Comment by chifflier** [comment]
Hi,
That's an interesting question. I've never tried, so I don't know if v1 is supported.
Looking at the ITU-T documents (https://www.itu.int/rec/T-REC-X.509/), it seems the most important difference is the addition of extensions, but the format looks basically the same.
It should not be difficult to add the support, there may be some parts that have to be marked optional, but that's all I can think of.

Do you have test files, or know how to generate them?

**Comment by chifflier** [comment]
Note: to generate v1 certificates, use openssl with a configuration file without extensions.

I can confirm v1 certificates are supported.

**Comment by amrx101** [comment]
@chifflier , Sorry for late response. Yup you are write, that a x509 cert generated with an openssl config missing the `v3 extensions` will be a version 1 certificate. 

I am trying to get TLS handshake working wherein the server certificate is v1. I hope I can use this as `Rustls` today only works with `v3` certs.
