### ISSUE TITLE
BasicConstraints can fail to parse

### ISSUE THREAD

**Issue by g2p** [rusticata/x509-parser#33]
The [following cert](https://github.com/rusticata/x509-parser/files/4846533/staging-eecert.der.gz) (issued by the LetsEncrypt staging CA) causes parse_basicconstraints to fail with nom Err::Incomplete (needs one more byte) when a complete certificate is passed to it. This also cascades into not parsing the rest of the extensions (see #32).

gunzip and test with

    cargo run --example print-cert staging-eecert.der

**Comment by chifflier** [comment]
Thanks for the test data! This helped a lot.

It turns out the bug is in fact not in `x509-parser`, but in `der-parser`: https://github.com/rusticata/der-parser/issues/27

**Comment by chifflier** [comment]
Fixed by upgrading to `der-parser` [4.0.1](https://crates.io/crates/der-parser/4.0.1)

**Comment by chifflier** [comment]
Hum, that was not correct, dc74b8d50054e1ff4a4d077d7cb49a289cdde5a0 is also required
Now the certificate is correctly parsed

**Comment by g2p** [comment]
Thank you very much!
