### ISSUE TITLE
Authority Key Identifier isn't parsed

### ISSUE THREAD

**Issue by ericseppanen** [rusticata/x509-parser#45]
Many of the common x509 extensions are parsed, but Authority Key Identifier isn't among them.

Is there any reason this extension isn't supported? Would this be an improvement that you'd accept a PR for?

**Comment by chifflier** [comment]
Hi,
There is no particular reason but lack of time, but I intend to add it. A PR would be welcome of course :)

**Comment by chifflier** [comment]
Support for AKI has been added.
Running more tests before closing

**Comment by ericseppanen** [comment]
Awesome, thanks!

**Comment by chifflier** [comment]
Added, and released in 0.8.0

If you encounter any problem please open a new issue.
