### ISSUE TITLE
Naming confusion: pem_to_der returns a Pem

### ISSUE THREAD

**Issue by nivekuil** [rusticata/x509-parser#53]
The lines in question: https://docs.rs/x509-parser/0.8.2/src/x509_parser/pem.rs.html#70-77

Hi, thanks for writing this package. I am not very familiar with x509 and I had some confusion trying to figure out the API. As far as I understand a PEM and a DER are mutually exclusive encodings, and I was confused that a function called x_to_y actually returns something of type x. I guess they're different at the byte level but share the same trait impl at the code level, but this is quite confusing to think about. I'm not familiar enough with this domain to suggest a better name, but I wanted to throw this out for future consideration.

**Comment by chifflier** [comment]
You're right, the name is not a good one. Originally, I wanted the name to express the fact the result is not a certificate, but a container of data that needs to be decoded again:
a PEM certifcate has to be decoded twice: once for PEM/base 64 container, and once for the DER data.

Maybe something like `parse_x509_pem` is a better name.

**Comment by chifflier** [comment]
Closing, this is now part of the future 0.9.0 release
