### ISSUE TITLE
Consider keeping struct definitions and parsers together

### ISSUE THREAD

**Issue by djc** [rusticata/x509-parser#60]
Right now it seems most type definitions live in the `x509` module whereas parsers live in `x509_parser`. It would make the code easier to follow and modify if parsers lived closer to the relevant type definitions, for example in an impl block (as in `fn from_bytes(i: &[u8]) -> X509Result<Self> {}`, for example).

**Comment by chifflier** [comment]
I tend to agree. Originally I did that to avoid having thousands of lines of parsing code mixed with type definitions (creating big and difficult to read files), but I can see why it makes difficult to know which function is available.

What do you think of keeping the parsers in `x509_parser.rs`, and add methods to `x509.rs`? Adding a common trait for all parsers would be nice

**Comment by djc** [comment]
I think a better way to split the modules would be to split them by some notion of semantics and then actually keeping the parsers and types together. For me the important part is that the type and the parser are typically tightly coupled (for example, if you want to change the fields of a type you have to change both), so having them live "far away" from each other is harder (and the method indirection doesn't help with that).

If you like I can do a PR proposal.

**Comment by chifflier** [comment]
Note: I thought of using `nom::Parser` (https://docs.rs/nom/6.0.0/nom/trait.Parser.html), but the big point is that it applies to an existing struct. A builder pattern would be required, creating types like `X509CertificateParser` with a method `parse` returning a `IResult<X509Certificate>
Pros:
- use nom common traits, so reusable elsewhere
- this allows configuring the parser / adding a context, which is currently not possible
Cons:
- adding new types, though it could be solved by creating a method `X509Certificate::from_bytes()` (or `::parse()`) calling `X509Parser()::parse()`

**Comment by djc** [comment]
Using a trait for construction is a little painful because you'd have to supply explicit type arguments. I don't see many advantages over just using `from_bytes()` associated functions.

**Comment by chifflier** [comment]
Adding `from_bytes` to all public structures would be exactly like using a trait :) I see that as useful for public functions, because it standardizes what you can expect. In particular, I have a crate for PKCS#7/CMS messages (not yet released) that needs to import many parsers from X.509.
That said, I do not have reasons to absolutely require traits. Maybe a solution is to go to functions, validate API, and look again at that point if traits are useful.

Do you want to give a try to the change you propose?

**Comment by djc** [comment]
Yup, I'll give it a shot.

**Comment by chifflier** [comment]
Fixed in #65, thanks!
