### ISSUE TITLE
Why does X509CertificationRequest::verify_signature take a parameter

### ISSUE THREAD

**Issue by est31** [rusticata/x509-parser#66]
In reviewing https://github.com/est31/rcgen/pull/41 I saw that the `verify_signature` function on CSRs taking a parameter, with None being passed in the PR. Fearing that the API witholding some feature that upstream provides, I checked the function definition. Apparently it's only to pass an optional public key to use for verification. For *certificates*, such a param makes sense, as they might be signed by other entities, but CSRs are always self-signed, no? What about removing the parameter from the API before a crates.io release?

cc @djc

**Comment by djc** [comment]
Probably just my mistake in blindly copying the Certificate verification code. I'll fix it up.

**Comment by djc** [comment]
See #67.
