### ISSUE TITLE
Where are all the OIDs?

### ISSUE THREAD

**Issue by faulesocke** [rusticata/x509-parser#68]
Version 0.9 used to contain a lot of predefined OIDs in `x509_parser::objects`. Now these are gone. Were they moved to some other crate or do I have to build them myself using the `der_parser::oid` macro?

**Comment by faulesocke** [comment]
I also could not find anything in the docs or the changelog about this.

**Comment by faulesocke** [comment]
After searching the code I found them in a separate crate called `oid_registry`. I would suggest that this gets mentioned in the docs.

**Comment by chifflier** [comment]
Hi,
The major OIDs were indeed moved to a crate `oid-registry`. This crate also allows extending the registry, so additional or specific OID can also be added in `x509-parser` when instantiating the registry.
I'll see how to document that.

**Comment by thalesfragoso** [comment]
@chifflier 

https://github.com/rusticata/x509-parser/blob/a00a8666cd2dfcc9780d1fbb2a09dbd5fe6caa82/src/objects.rs#L8

Could you just change this to `pub use` so we can get easy access to the OID constants ?

**Comment by chifflier** [comment]
I added some documentation in the `object` module with an example, and re-exported `oid-registry`.
This should address both problems.
Thanks!
