### ISSUE TITLE
Docs try to link to x509/x509Certificate, but that struct is in the certificate module

### ISSUE THREAD

**Issue by saethlin** [rusticata/x509-parser#74]
This is the first of the broken links, but there's a few more: https://github.com/rusticata/x509-parser/blob/9371074698ec2c51766bbab362523499f9c05af8/src/lib.rs#L27

I feel like there ought to be a lint to prevent this from happening?

**Comment by chifflier** [comment]
Thanks for the report, I'll check links in documentation again.

I have enabled a lint (in the same file): https://github.com/rusticata/x509-parser/blob/9371074698ec2c51766bbab362523499f9c05af8/src/lib.rs#L118 in the same file, but apparently it did not catch this link.
