### ISSUE TITLE
Missing oid2description() function

### ISSUE THREAD

**Issue by lilyball** [rusticata/x509-parser#79]
This crate uses an `OidRegistry` internally, and provides an `oid2sn()` function, but does not provide any way to get at the oid description. This is unfortunate, because I don't want to have to maintain my own separate `OidRegistry` with all of the same entries as that seems like a waste of memory (and it also means I'd get out of sync if this crate ever adds any new oids to its own registry). This crate should either provide an `oid2description()` function, or perhaps just provide a function that returns a reference to its internal `OidRegistry` that I can use to look up stuff directly. The latter approach would also let me do things like iterate over all known oids.

**Comment by chifflier** [comment]
Thanks for your suggestions, they're both fine so I'll add both `oid2description()` and `oid_registry()` (to get a ref to the registry).

In fact, it would be even nicer to allow a write access to the registry (so callers could extend the registry without maintaining their own), but this would mean adding locks on every access :/
