### ISSUE TITLE
x509_parser::extensions::PolicyMappings confusing, discards order

### ISSUE THREAD

**Issue by lilyball** [rusticata/x509-parser#82]
The `x509_parser::extensions::PolicyMappings` type is rather confusing as it represents a sequence of tuples `(issuerDomainPolicy, subjectDomainPolicy)`, but it's implemented as a `HashMap<Oid<'a>, Vec<Oid<'a>>>` with no documentation.

Reading the source tells me that the keys are the issuer domain policies, and the values are all of the subject domain policies that occur with the issuer domain policy, i.e. an input sequence `[(a, b), (a, c)]` produces the output `{a: [b, c]}`. But this is completely undocumented, and it also discards ordering (which matters for deterministic output when printing certificate details).

At a bare minimum, this needs documentation. But really, this should just be represented as something like `Vec((Oid<'a>, Oid<'a>))`. I can convert this into a `HashMap` myself if I need to.

BTW this is the second such ticket about a sequence being converted to a `HashMap` and discarding order. I'm not sure offhand if any other such conversions exist, but if so, I would really prefer to just get ordered sequences across the board, so I can print certificate details in a deterministic and predictable manner (and so I can generate new modified certificates while minimizing unnecessary changes such as ordering).

**Comment by chifflier** [comment]
Agreed, losing the order of items is not desirable. I am also in favor of returning a `Vec` (maybe adding helper functions to build and return a `HashMap` if this is useful).
Changing this will break the API, and will be planned for the next release.
