### ISSUE TITLE
x509_parser::objects::OID_REGISTRY is not public

### ISSUE THREAD

**Issue by JackLiar** [rusticata/x509-parser#88]
```rust
static ref OID_REGISTRY: OidRegistry<'static> = {
        let reg = OidRegistry::default().with_all_crypto().with_x509();
        // OIDs not in the default registry can be added here
        reg
    };
```

**Comment by chifflier** [comment]
Hi,
The `oid2sn` and `oid2abbrev` functions acts as accessors for the registry. Do you have any use case that is not covered, or reason to expose the registry directly?

**Comment by JackLiar** [comment]
Well there are 2 reasons:
1. The comment said `OIDs not in the default registry can be added here`, so I suppose maybe this is meant to be public, but forgotten
2. When handling a cert's subjectPublicKeyInfo's ECParameters, there is a kind called namedCurve(could be parsed and translated by Wireshark), and it is OID formatted. I found the one I'm testing with is not covered, so I think maybe there are lots of other curves not covered by oid_registry.

For the second reason, sure I could use a totally independent oid registry to cover it, but it would be better to use only one instance to reduce memory usage and redundant codes.

**Comment by chifflier** [comment]
I see, thanks for the reply.
The `oid_registry()` function now returns a reference to the registry (d830cce502a3717b58bd7232efd12491a17bb801).

I'm still wondering what the best solution would be, to allow modifying/extending the registry without adding locks everywhere

**Comment by JackLiar** [comment]
I think it's too much burden for a crate to cover all these usage conditions, why not just provide a function that accept a mutable reference to an oid registry(`&mut OidRegistry<'a>`) and initialize/modify it with internal predefined OIDs. User could use any form lock or mutex as they choice. Though this requires `oid2sn` and other functions to accept an extra argument. After all, what users really want is those predefined OIDs, then is a convenient api. And if the default OIDs are enough for some users, they could enable a crate feature(for example named: "internal-oid-registry") to gain a default internal oid registry and use the old api just like the old times.
