### ISSUE TITLE
Fix parsing for CRLDistributionPoints

### ISSUE THREAD

**Issue by chifflier** [rusticata/x509-parser#97]
Followup from #96

**Comment by chifflier** [comment]
After first analysis, it seems the `reasons` field is strangely encoded in the test certificate:
- it is encoded as `81 03 07 60 80`, which is a tagged value with constructed bit *not* set
- it should have been `a1 03 ...`

`X.690 section 8.14.2` says that `If implicit tagging [...] was not used [...] the encoding shall be constructed`.

So the first interpretation is that openssl generates an encoded value that is not strictly compliant to DER.

**Comment by chifflier** [comment]
After more investigations, the problem seems to be that openssl uses IMPLICIT tagging instead of EXPLICIT.
This may be an openssl bug, I'll report it to them.

**Comment by chifflier** [comment]
IMPLICIT tagging should have been used everywhere, but it seems the first field is explicit.
It may be an openssl error (to be verified)

**Comment by xonatius** [comment]
Thank you for the fix! I think this can be closed now (:
